**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/getting-started-with-sql-and-bigquery).**

---

# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

In [21]:
# Set up feedack system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex1 import *
print("Setup Complete")

Setup Complete

Use the next code cell to fetch the dataset.

In [22]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

Using Kaggle's public dataset BigQuery integration.

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [23]:
# Write the code you need here to figure out the answer
# List all the tables in the "hacker_news" dataset
tables = list(client.list_tables(dataset))

# Print names of all tables in the dataset (there are four!)
for table in tables:  
    print(table.table_id)

crime

In [24]:
num_tables = 1  # Store the answer as num_tables and then run this cell

# Check your answer
q_1.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [25]:
#q_1.hint()
#q_1.solution()

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [26]:
# Write the code to figure out the answer
# Construct a reference to the "full" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

In [27]:
#counting by gathering the information of the table
table.schema

[SchemaField('unique_key', 'INTEGER', 'REQUIRED', 'Unique identifier for the record.', ()),
 SchemaField('case_number', 'STRING', 'NULLABLE', 'The Chicago Police Department RD Number (Records Division Number), which is unique to the incident.', ()),
 SchemaField('date', 'TIMESTAMP', 'NULLABLE', 'Date when the incident occurred. this is sometimes a best estimate.', ()),
 SchemaField('block', 'STRING', 'NULLABLE', 'The partially redacted address where the incident occurred, placing it on the same block as the actual address.', ()),
 SchemaField('iucr', 'STRING', 'NULLABLE', 'The Illinois Unifrom Crime Reporting code. This is directly linked to the Primary Type and Description. See the list of IUCR codes at https://data.cityofchicago.org/d/c7ck-438e.', ()),
 SchemaField('primary_type', 'STRING', 'NULLABLE', 'The primary description of the IUCR code.', ()),
 SchemaField('description', 'STRING', 'NULLABLE', 'The secondary description of the IUCR code, a subcategory of the primary description.', ()),
 SchemaField('location_description', 'STRING', 'NULLABLE', 'Description of the location where the incident occurred.', ()),
 SchemaField('arrest', 'BOOLEAN', 'NULLABLE', 'Indicates whether an arrest was made.', ()),
 SchemaField('domestic', 'BOOLEAN', 'NULLABLE', 'Indicates whether the incident was domestic-related as defined by the Illinois Domestic Violence Act.', ()),
 SchemaField('beat', 'INTEGER', 'NULLABLE', 'Indicates the beat where the incident occurred. A beat is the smallest police geographic area â€“ each beat has a dedicated police beat car. Three to five beats make up a police sector, and three sectors make up a police district. The Chicago Police Department has 22 police districts. See the beats at https://data.cityofchicago.org/d/aerh-rz74.', ()),
 SchemaField('district', 'INTEGER', 'NULLABLE', 'Indicates the police district where the incident occurred. See the districts at https://data.cityofchicago.org/d/fthy-xz3r.', ()),
 SchemaField('ward', 'INTEGER', 'NULLABLE', 'The ward (City Council district) where the incident occurred. See the wards at https://data.cityofchicago.org/d/sp34-6z76.', ()),
 SchemaField('community_area', 'INTEGER', 'NULLABLE', 'Indicates the community area where the incident occurred. Chicago has 77 community areas. See the community areas at https://data.cityofchicago.org/d/cauq-8yn6.', ()),
 SchemaField('fbi_code', 'STRING', 'NULLABLE', "Indicates the crime classification as outlined in the FBI's National Incident-Based Reporting System (NIBRS). See the Chicago Police Department listing of these classifications at http://gis.chicagopolice.org/clearmap_crime_sums/crime_types.html.", ()),
 SchemaField('x_coordinate', 'FLOAT', 'NULLABLE', 'The x coordinate of the location where the incident occurred in State Plane Illinois East NAD 1983 projection. This location is shifted from the actual location for partial redaction but falls on the same block.', ()),
 SchemaField('y_coordinate', 'FLOAT', 'NULLABLE', 'The y coordinate of the location where the incident occurred in State Plane Illinois East NAD 1983 projection. This location is shifted from the actual location for partial redaction but falls on the same block.', ()),
 SchemaField('year', 'INTEGER', 'NULLABLE', 'Year the incident occurred.', ()),
 SchemaField('updated_on', 'TIMESTAMP', 'NULLABLE', 'Date and time the record was last updated.', ()),
 SchemaField('latitude', 'FLOAT', 'NULLABLE', 'The latitude of the location where the incident occurred. This location is shifted from the actual location for partial redaction but falls on the same block.', ()),
 SchemaField('longitude', 'FLOAT', 'NULLABLE', 'The longitude of the location where the incident occurred. This location is shifted from the actual location for partial redaction but falls on the same block.', ()),
 SchemaField('location', 'STRING', 'NULLABLE', 'The location where the incident occurred in a format that allows for creation of maps and other geographic operations on this data portal. This location is shifted from the actual location for partial redaction but falls on the same block.', ())]

In [28]:
# Preview the first five lines of the "full" table
client.list_rows(table, max_results=5).to_dataframe()

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,10911364,JA224025,2014-08-27 16:00:00+00:00,052XX W 64TH PL,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,...,13,64,17,None,None,2014,2017-04-14 15:50:04+00:00,None,None,None
1,7954954,HT186714,2003-01-01 00:01:00+00:00,101XX S WESTERN AVE,1140,DECEPTIVE PRACTICE,EMBEZZLEMENT,OTHER,False,False,...,19,72,12,None,None,2003,2015-08-17 15:03:40+00:00,None,None,None
2,11131682,JA487070,2016-01-01 00:01:00+00:00,113XX S AVENUE H,1753,OFFENSE INVOLVING CHILDREN,SEX ASSLT OF CHILD BY FAM MBR,RESIDENCE,False,False,...,10,52,02,None,None,2016,2017-10-28 15:52:30+00:00,None,None,None
3,9762519,HX412511,2006-01-08 10:00:00+00:00,018XX S LA SALLE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,False,False,...,25,34,11,None,None,2006,2015-08-17 15:03:40+00:00,None,None,None
4,11713981,JC295716,2017-09-15 09:00:00+00:00,067XX N DOWAGIAC AVE,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,OTHER,False,False,...,41,12,26,None,None,2017,2019-06-07 16:05:48+00:00,None,None,None

In [29]:
num_timestamp_fields = 2 # Put your answer here

# Check your answer
q_2.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [30]:
#q_2.hint()
#q_2.solution()

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [35]:
# Write the code here to explore the data so you can find the answer
client.list_rows(table, max_results = 10).to_dataframe()

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,10911364,JA224025,2014-08-27 16:00:00+00:00,052XX W 64TH PL,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,...,13,64,17,NaN,NaN,2014,2017-04-14 15:50:04+00:00,NaN,NaN,None
1,7954954,HT186714,2003-01-01 00:01:00+00:00,101XX S WESTERN AVE,1140,DECEPTIVE PRACTICE,EMBEZZLEMENT,OTHER,False,False,...,19,72,12,NaN,NaN,2003,2015-08-17 15:03:40+00:00,NaN,NaN,None
2,11131682,JA487070,2016-01-01 00:01:00+00:00,113XX S AVENUE H,1753,OFFENSE INVOLVING CHILDREN,SEX ASSLT OF CHILD BY FAM MBR,RESIDENCE,False,False,...,10,52,02,NaN,NaN,2016,2017-10-28 15:52:30+00:00,NaN,NaN,None
3,9762519,HX412511,2006-01-08 10:00:00+00:00,018XX S LA SALLE ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,False,False,...,25,34,11,NaN,NaN,2006,2015-08-17 15:03:40+00:00,NaN,NaN,None
4,11713981,JC295716,2017-09-15 09:00:00+00:00,067XX N DOWAGIAC AVE,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,OTHER,False,False,...,41,12,26,NaN,NaN,2017,2019-06-07 16:05:48+00:00,NaN,NaN,None
5,11728711,JC313641,2019-06-19 20:40:00+00:00,010XX E 90TH ST,0498,BATTERY,AGGRAVATED DOMESTIC BATTERY: HANDS/FIST/FEET S...,RESIDENCE,False,True,...,8,47,04B,1184896.0,1845523.0,2019,2019-07-11 16:09:54+00:00,41.731271,-87.598243,"(41.731270501, -87.598243074)"
6,11718911,JC301713,2019-06-11 09:00:00+00:00,103XX S CHURCH ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,"SCHOOL, PUBLIC, GROUNDS",False,False,...,19,72,26,1168069.0,1836274.0,2019,2019-06-30 15:56:27+00:00,41.706268,-87.660151,"(41.706267651, -87.660151417)"
7,11725358,JC309736,2019-06-15 00:00:00+00:00,058XX N ST JOHNS CT,1156,DECEPTIVE PRACTICE,ATTEMPT - FINANCIAL IDENTITY THEFT,OTHER,False,False,...,39,12,11,1146654.0,1938708.0,2019,2019-06-30 15:56:27+00:00,41.987793,-87.735964,"(41.987792784, -87.735963789)"
8,11725420,JC309792,2019-06-17 09:17:00+00:00,131XX S AVENUE O,502R,OTHER OFFENSE,VEHICLE TITLE/REG OFFENSE,STREET,False,False,...,10,55,26,1201075.0,1818368.0,2019,2019-06-30 15:56:27+00:00,41.656360,-87.539891,"(41.656360251, -87.539891023)"
9,11732972,JC318871,2019-06-23 19:24:00+00:00,114XX S FORRESTVILLE AVE,502P,OTHER OFFENSE,FALSE/STOLEN/ALTERED TRP,STREET,True,False,...,9,50,26,1181970.0,1828886.0,2019,2019-06-30 16:13:20+00:00,41.685685,-87.609474,"(41.685684509, -87.60947432)"

In [ ]:
fields_for_plotting = ['longitude', 'latitude'] # Put your answers here

# Check your answer
q_3.check()

For a hint or the solution, uncomment the appropriate line below.

In [ ]:
#q_3.hint()
#q_3.solution()

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [ ]:
# Scratch space for your code

# Keep going

You've looked at the schema, but you haven't yet done anything exciting with the data itself. Things get more interesting when you get to the data, so keep going to **[write your first SQL query](https://www.kaggle.com/dansbecker/select-from-where).**

---




*Have questions or comments? Visit the [Learn Discussion forum](https://www.kaggle.com/learn-forum/161314) to chat with other Learners.*